appname: "default-app"

namespace: "default"

environment: "dev"

replicas: 3

containername: "default-container"

image: "latest"

containerport: 8080

serviceport: 80

servicetype: "ClusterIP"

hpa:
  enabled: true

  minReplicas: 1

  maxReplicas: 3

  targetCPUUtilizationPercentage: 50

  targetMemoryUtilizationPercentage: 50

pdb:
  enabled: true

  minAvailable: 1

configmapdata:
  # vi du da roi chinh sau
  DATABASE_URL: "postgres://default:5432/mydb"
  LOG_LEVEL: "info"
  APP_MODE: "production"
