apiVersion:apps/v1
kind:Deployment
metadata:
  name : {{.Values.appname}}-deployment
  namespace:{{.Values.namespace}}
  labels :
    {{- include "base-service.labels" . | nindent 4}}
spec :
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      {{- include "base-service.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "base-service.labels" . | nindent 8}}
    spec:
      containers:
      - name:{{.Values.containername}}
        image:{{.Values.image}}
        ports:
        - containerPort:{{.Values.containerport}}

        a

      

