apiVersion:v1
kind:Service
metadata:
  name:{{.Values.appname}}-service
  namespace:{{.Values.namespace}}
  labels:
    {{- include "base-service.labels" . | nindent 4}}
spec:
  type: {{.Values.servicetype}}
  selector:
    {{- include "base-service.selectorLabels" . | nindent 4}}
  ports:
  - port:{{.Values.serviceport}}
    targetPort:{{.Values.containerport}}a